In [1]:
import numpy as np
import tensorflow as tf
from environment import Environment
from actor import Actor

2023-11-25 10:08:17.631607: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-25 10:08:17.767003: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-25 10:08:17.767038: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-25 10:08:17.794865: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-25 10:08:17.855452: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-25 10:08:17.856333: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [ ]:
    def build_train_step(self):
        '''
        This function returns a train_step op, in which by running it we proceed one training step.
        '''
        args = self.args
        
        R, v, logprobs, actions, idxs , batch , probs= self.train_summary

        v_nograd = tf.stop_gradient(v)
        R = tf.stop_gradient(R)

        # losses
        actor_loss = tf.reduce_mean(tf.multiply((R-v_nograd), tf.add_n(logprobs)),0)
        critic_loss = tf.losses.mean_squared_error(R,v)

        # optimizers
        actor_optim = tf.train.AdamOptimizer(args['actor_net_lr'])
        critic_optim = tf.train.AdamOptimizer(args['critic_net_lr'])

        # compute gradients
        actor_gra_and_var = actor_optim.compute_gradients(actor_loss,\
                                tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES, scope='Actor'))
        critic_gra_and_var = critic_optim.compute_gradients(critic_loss,\
                                tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES, scope='Critic'))

        # clip gradients
        clip_actor_gra_and_var = [(tf.clip_by_norm(grad, args['max_grad_norm']), var) \
                                  for grad, var in actor_gra_and_var]

        clip_critic_gra_and_var = [(tf.clip_by_norm(grad, args['max_grad_norm']), var) \
                                  for grad, var in critic_gra_and_var]

        # apply gradients
        actor_train_step = actor_optim.apply_gradients(clip_actor_gra_and_var)
        critic_train_step = critic_optim.apply_gradients(clip_critic_gra_and_var)

In [84]:
n_samples = 5
n_locations = 10
max_demand = 10
max_capacity = 20
env = Environment(n_samples, n_locations, max_demand, max_capacity)
act = Actor(n_locations)
optimizer = tf.keras.optimizers.Adam()

In [85]:
def reward_func(sample_solution):
    # make init_solution of shape [sourceL x batch_size x input_dim]
    # make sample_solution of shape [sourceL x batch_size x input_dim]
    sample_solution = tf.stack(sample_solution,0)

    sample_solution_tilted = tf.concat((tf.expand_dims(sample_solution[-1],0),
         sample_solution[:-1]),0)
    # get the reward based on the route lengths


    route_lens_decoded = tf.reduce_sum(tf.pow(tf.reduce_sum(tf.pow(\
        (sample_solution_tilted - sample_solution) ,2), 2) , .5), 0)
    return route_lens_decoded

In [98]:
def softargmax(x, beta=1e10):
  x = tf.convert_to_tensor(x)
  x_range = tf.range(x.shape.as_list()[-1], dtype=x.dtype)
  return tf.reduce_sum(tf.nn.softmax(x*beta) * x_range, axis=1)

In [175]:
class Critic(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.dense_1 = tf.keras.layers.Dense(64)
        self.dense_2 = tf.keras.layers.Dense(64)
        self.dense_3 = tf.keras.layers.Dense(64)
        self.dense_4 = tf.keras.layers.Dense(1)

    def call(self, x):
        x = self.dense_1(x)
        x = self.dense_2(x)
        x = self.dense_3(x)
        x = self.dense_4(x)

        return x

In [183]:
cr = Critic()

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[-0.7488811],
       [-0.7488811],
       [-0.7488811],
       [ 0.       ],
       [ 0.       ]], dtype=float32)>

In [241]:
with tf.GradientTape(persistent=True) as tape:
    range_idx = tf.expand_dims(tf.range(n_samples, dtype=tf.float32), 1)
    range_idx = tf.constant([[0], [1], [2], [3], [4.0]])
    tape.watch(range_idx)
    
    actions = []
    for i in range(5):
        logits = act(env, training=True)
        idx = tf.argmax(logits, 1)
        # state = env.update_state(idx)
        idx2 = softargmax(logits)
        
        logits2 = tf.tile(tf.expand_dims(logits, -1), [1, 1, 2])
        
        # prob = tf.nn.softmax(logits)
        # prob2 = softargmax(logits)
        abc = tf.constant([0, 1, 2, 3, 4, 5, 6, 7, 8])[idx[0]]
        
        cr_loss = cr(tf.expand_dims(idx2, -1))
        
        argmax_idx2 = tf.cast(
            tf.concat(
                [range_idx, tf.expand_dims(tf.cast(idx2, tf.float32), -1)], 1),
            dtype=tf.int32
        )
        action = tf.gather_nd(tf.tile(env.locations, [env.n_samples, 1, 1]), argmax_idx2)
        
        actions.append(action)
        break
        
    
    R = reward_func(actions)
    
    actor_loss = tf.reduce_max(env.locations * logits2)

grads = tape.gradient(actor_loss, act.trainable_variables)

In [246]:
env.locations

<tf.Tensor: shape=(5, 10, 2), dtype=float32, numpy=
array([[[-0.905458  , -0.78969693],
        [-0.91376543,  0.30174947],
        [ 0.13879061, -0.38170743],
        [-0.10857105,  0.54305625],
        [ 0.8574586 ,  0.18924093],
        [-0.9771397 ,  0.58238673],
        [ 0.6275978 ,  0.6831989 ],
        [-0.13148451,  0.13998675],
        [-0.48911285,  0.01230454],
        [-0.53770447, -0.00589275]],

       [[ 0.8734143 ,  0.95403504],
        [ 0.20120144,  0.00952387],
        [-0.3508761 , -0.37942767],
        [-0.6408088 , -0.39353395],
        [ 0.3153627 ,  0.07364631],
        [ 0.8688843 ,  0.5672972 ],
        [-0.8013754 , -0.3706696 ],
        [-0.9302139 , -0.7275672 ],
        [-0.6406729 ,  0.61462235],
        [ 0.4915018 ,  0.32411456]],

       [[-0.13438606,  0.8021157 ],
        [-0.7473235 ,  0.15579438],
        [ 0.5671828 ,  0.7401273 ],
        [ 0.9069383 ,  0.5466025 ],
        [-0.8521633 ,  0.18376589],
        [-0.29691124,  0.03248906],
        

In [244]:
logits

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[ 2.1797423 ,  0.88463026, -4.712718  , -0.86078334, -0.14114107,
        -3.6585312 , -0.9642631 , -2.335124  ,  2.201816  ,  1.4401883 ],
       [ 0.32978612, -1.6594005 , -0.57094795,  1.0643724 ,  1.0822908 ,
        -1.3862207 , -0.38778475, -0.70239943,  3.8274894 , -0.5483512 ],
       [ 5.5095205 , -4.002549  , -6.637522  ,  1.9680909 , -3.4044437 ,
        -3.134617  , -0.20703422, -7.315778  ,  7.14723   , -4.82431   ],
       [ 5.664192  ,  0.46633065, -1.6837324 ,  3.0121737 , -5.4986205 ,
        -4.14644   ,  4.0082335 , -3.4577703 ,  5.3663144 , -1.0311953 ],
       [ 2.5666242 , -0.16718435, -4.7819676 ,  1.4847906 , -0.08832158,
        -1.7794033 ,  0.65105647, -1.03809   ,  0.838561  , -0.5448495 ]],
      dtype=float32)>

In [243]:
grads

[<tf.Tensor: shape=(10, 64), dtype=float32, numpy=
 array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.000

<tf.Tensor: shape=(5, 10, 2), dtype=float32, numpy=
array([[[-1.9736651 , -1.7213359 ],
        [-0.80834454,  0.26693672],
        [-0.654081  ,  1.7988795 ],
        [ 0.09345616, -0.46745378],
        [-0.12102263, -0.02670967],
        [ 3.574896  , -2.13068   ],
        [-0.6051694 , -0.6587835 ],
        [ 0.30703264, -0.32688642],
        [-1.0769366 ,  0.02709234],
        [-0.7743957 , -0.00848668]],

       [[ 0.2880399 ,  0.31462753],
        [-0.33387375, -0.01580391],
        [ 0.20033199,  0.21663345],
        [-0.6820592 , -0.41886666],
        [ 0.34131414,  0.07970672],
        [-1.2044654 , -0.7863991 ],
        [ 0.31076115,  0.14374001],
        [ 0.65338176,  0.5110428 ],
        [-2.4521687 ,  2.3524606 ],
        [-0.26951563, -0.17772862]],

       [[-0.74040276,  4.419273  ],
        [ 2.991199  , -0.6235747 ],
        [-3.7646883 , -4.9126115 ],
        [ 1.784937  ,  1.0757633 ],
        [ 2.9011421 , -0.6256206 ],
        [ 0.93070304, -0.10184076],
        

In [222]:
tf.reshape(logits, (5, 1, 10)).shape

TensorShape([5, 1, 10])

TensorShape([5, 2, 10])

In [213]:
logits.shape

TensorShape([5, 10])

In [206]:
indices = tf.constant(tf.cast(tf.expand_dims(idx2, -1), dtype=tf.int32))
updates = tf.ones(shape=5, dtype=tf.float32)
scatter = tf.scatter_nd(indices, updates, [5, 10])
scatter

InvalidArgumentError: {{function_node __wrapped__ScatterNd_device_/job:localhost/replica:0/task:0/device:CPU:0}} Dimensions [1,2) of input[shape=[5,10]] must match dimensions [1,1) of updates[shape=[5]] [Op:ScatterNd]

In [207]:
indices

<tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[8],
       [8],
       [8],
       [0],
       [0]], dtype=int32)>

In [210]:
indices2

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[4],
       [3],
       [1],
       [7]], dtype=int32)>

In [209]:
indices2 = tf.constant([[4], [3], [1], [7]])
updates2 = tf.constant([9, 10, 11, 12.0])
shape2 = tf.constant([8])
scatter2 = tf.scatter_nd(indices2, updates2, shape2)

In [203]:
indices

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[4],
       [3],
       [1],
       [7]], dtype=int32)>

In [194]:
indices

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[8.],
       [8.],
       [8.],
       [0.],
       [0.]], dtype=float32)>

In [ ]:
tf.scatter_nd()

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([8., 8., 8., 0., 0.], dtype=float32)>

In [187]:
grads

[<tf.Tensor: shape=(10, 64), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [28]:
idx = np.array([0, 2, 1])

BatchSequence = tf.expand_dims(tf.cast(tf.range(3), tf.int64), 1)

batched_idx = tf.concat([BatchSequence, idx.reshape(-1, 1)], 1)

In [393]:
with tf.GradientTape(persistent=True) as gradient_tape:
    res = act(env)
    res2 = act(env)
    argmax = tf.argmax(res, 1)
    argmax2 = tf.argmax(res2, 1)
    
    range_idx = tf.expand_dims(tf.range(n_samples, dtype=tf.float32), 1)
    argmax_idx = tf.cast(
        tf.concat(
            [range_idx, tf.expand_dims(tf.cast(argmax, tf.float32), -1)], 1),
        dtype=tf.int32
    )

    argmax_idx2 = tf.cast(
        tf.concat(
            [range_idx, tf.expand_dims(tf.cast(argmax2, tf.float32), -1)], 1),
        dtype=tf.int32
    )
    
    # old_locations_idx = tf.cast(
    #     tf.concat(
    #         [range_idx, np.array([0] * n_samples).reshape(n_samples, 1)], 1
    #     ),
    #     dtype=tf.int32
    # )
    # old_locations = tf.zeros(shape=new_locations.shape) # tf.gather_nd(env.locations, old_locations_idx)
    new_locations = tf.gather_nd(env.locations, argmax_idx)
    old_locations = tf.gather_nd(env.locations, argmax_idx2)
    
    loss = tf.reduce_sum(new_locations - old_locations)
    
gradients = gradient_tape.gradient(tf.constant(loss), act.trainable_variables)
grads_and_vars = zip(gradients, act.trainable_variables)
optimizer.apply_gradients(grads_and_vars)

ValueError: No gradients provided for any variable: (['actor_2/dense_8/kernel:0', 'actor_2/dense_8/bias:0', 'actor_2/dense_9/kernel:0', 'actor_2/dense_9/bias:0', 'actor_2/dense_10/kernel:0', 'actor_2/dense_10/bias:0', 'actor_2/dense_11/kernel:0', 'actor_2/dense_11/bias:0'],). Provided `grads_and_vars` is ((None, <tf.Variable 'actor_2/dense_8/kernel:0' shape=(10, 64) dtype=float32, numpy=
array([[ 1.60265326e-01,  1.01168007e-01,  1.31321818e-01,
        -2.10709125e-01, -1.95295185e-01,  2.17770904e-01,
         1.09577447e-01, -1.44582689e-02,  1.45250022e-01,
         1.07636690e-01, -2.26784050e-01,  3.26275527e-02,
        -1.03380114e-01,  2.50906378e-01,  1.77229851e-01,
        -1.77407578e-01,  2.44342357e-01,  4.06339765e-02,
         2.44153172e-01,  7.10038841e-02, -1.00888520e-01,
        -1.17701113e-01,  1.97643548e-01, -6.61384165e-02,
         2.53881544e-01, -8.26842040e-02, -2.78604597e-01,
         2.32795447e-01,  2.70272881e-01,  1.43675476e-01,
         8.66126120e-02, -1.92492396e-01, -5.01967669e-02,
        -1.61322057e-02,  2.56520122e-01, -2.05570206e-01,
         2.44290799e-01, -1.33638978e-02, -2.24474251e-01,
         2.69186348e-01,  1.16746783e-01, -1.30019113e-01,
        -1.43425435e-01, -2.15824574e-01, -1.13427162e-01,
         2.49679714e-01,  1.14022344e-01,  3.20099592e-02,
        -6.74044788e-02, -1.29507899e-01, -2.42600635e-01,
        -8.61866027e-02,  1.90331906e-01,  2.34035879e-01,
         2.47771174e-01,  1.59939528e-01,  6.55995011e-02,
        -1.54343486e-01,  1.19733989e-01,  1.72951669e-01,
         1.08953118e-01, -1.30232558e-01,  1.66476965e-02,
        -2.20680535e-01],
       [ 8.49920958e-02, -1.91217706e-01, -2.35775620e-01,
        -1.61009222e-01,  2.38262340e-01, -2.20469907e-01,
         2.18211055e-01, -2.42543966e-01,  1.91117153e-01,
         1.53984040e-01, -4.02788818e-02,  2.08525106e-01,
        -1.52181566e-01,  2.79474527e-01, -2.42726445e-01,
        -1.34081170e-01, -2.48297036e-01, -6.47654086e-02,
         1.61099806e-01, -2.21516654e-01, -4.36524823e-02,
        -1.92788810e-01,  2.57210255e-01,  2.62099504e-01,
        -1.92995399e-01,  1.81932554e-01, -2.42647663e-01,
         8.57954994e-02,  1.92595914e-01,  1.75257400e-01,
        -1.02676056e-01,  2.29904894e-02, -4.13544960e-02,
         2.17285350e-01,  6.92631900e-02, -1.50512502e-01,
         3.55021621e-04,  2.77229697e-01, -1.54746488e-01,
        -2.38980919e-01,  1.65022030e-01,  1.18582800e-01,
         1.09710276e-01, -2.87719686e-02, -1.12017713e-01,
         2.46121198e-01, -5.38999401e-02, -8.40720311e-02,
        -1.25989810e-01,  1.31482691e-01,  2.30480224e-01,
         1.13193318e-01, -2.71359295e-01, -6.74321651e-02,
         2.05156788e-01, -8.83977935e-02, -1.33425653e-01,
        -2.44541720e-01, -5.79376593e-02,  2.84558255e-03,
        -2.34142110e-01,  2.08732769e-01, -4.63153049e-02,
         1.29430927e-02],
       [ 2.71438360e-01,  2.79889882e-01,  2.46416733e-01,
         1.09753855e-01, -8.27100724e-02, -7.69835711e-02,
         1.99792206e-01, -2.50366420e-01,  1.23278260e-01,
        -2.14152783e-01,  2.18762040e-01, -6.96705952e-02,
         2.37489253e-01,  1.71391711e-01,  1.60086155e-01,
         2.98235975e-02, -2.97013372e-02, -1.77222297e-01,
        -5.09635620e-02,  3.38968113e-02, -8.84592757e-02,
         2.10051760e-01, -1.52437568e-01,  1.22093126e-01,
        -2.84606852e-02,  9.09351259e-02,  1.17869318e-01,
         1.16351672e-01,  1.25347063e-01, -2.65469551e-01,
         1.29177086e-02, -1.80733521e-02,  2.14025602e-02,
        -2.37854317e-01,  1.22119505e-02, -1.44094199e-01,
        -1.19550034e-01,  2.07063764e-01,  2.41077691e-01,
        -2.08249241e-01,  2.48407587e-01,  2.61832267e-01,
        -8.59547257e-02,  4.95139696e-02, -2.25111261e-01,
         2.38860734e-02, -1.37538731e-01,  3.33169326e-02,
         5.52856503e-03,  2.76506364e-01, -5.12785055e-02,
        -2.13861689e-01, -2.49805123e-01, -1.91422120e-01,
         5.31612337e-02,  2.20563918e-01, -9.04672742e-02,
        -1.43474251e-01,  2.34706864e-01,  2.15633005e-01,
         8.44042152e-02,  2.75859624e-01, -2.73750901e-01,
        -1.52912065e-01],
       [ 2.66867638e-01,  2.08645221e-02,  2.24076554e-01,
        -5.19903637e-02,  1.59967110e-01,  2.87394635e-02,
         2.55044311e-01,  1.57280847e-01, -2.97640022e-02,
        -2.27016099e-02, -1.62552178e-01, -7.80870840e-02,
        -5.87402210e-02,  3.45590618e-03,  2.67768115e-01,
         1.67641610e-01, -1.68217182e-01,  4.85337675e-02,
        -1.54121011e-01, -4.45422754e-02,  5.23884222e-02,
         2.71962285e-01,  1.74141973e-01, -2.43138179e-01,
        -1.69120446e-01, -2.86396980e-01,  1.96727052e-01,
         1.95113033e-01,  3.41256745e-02,  2.04572931e-01,
         2.15926975e-01,  2.56885272e-02,  1.22913830e-01,
         9.78939906e-02,  1.27452493e-01, -1.91477109e-02,
        -2.30035018e-02,  1.23182938e-01, -7.98113644e-02,
         2.36951232e-01, -2.32968330e-01,  2.21602872e-01,
        -2.41208136e-01, -1.73060074e-01,  2.59182036e-01,
        -1.69994578e-01, -9.90689024e-02, -1.61737531e-01,
         2.03312904e-01,  1.22519158e-01,  1.97549284e-01,
         1.76159516e-02,  5.17687127e-02, -2.41467088e-01,
         2.82239635e-02, -1.92722538e-04,  2.81103224e-01,
         1.59362890e-03, -1.69085100e-01,  2.32401162e-01,
         2.41957456e-01, -1.58143431e-01,  9.47528258e-02,
         1.43978223e-01],
       [-2.86209136e-02,  1.20084085e-01, -2.23567873e-01,
         2.75276244e-01,  2.07039639e-02,  1.47773907e-01,
         1.84268981e-01, -8.72423407e-03,  1.31458625e-01,
        -6.35254681e-02, -1.51127949e-01, -1.53128996e-01,
        -2.73619354e-01, -4.06119786e-02,  1.06096059e-01,
         1.84550464e-01, -1.09491840e-01,  1.53626785e-01,
         2.23618165e-01,  1.46229461e-01,  2.55701840e-01,
        -1.88954547e-01, -2.19037831e-01,  1.45451114e-01,
         4.21770988e-03,  1.78183243e-01,  1.39206544e-01,
        -1.75827388e-02, -5.76322488e-02, -7.58275241e-02,
        -1.46584660e-01,  1.95233285e-01, -9.03689191e-02,
        -1.40244499e-01, -2.23076299e-01, -3.18730362e-02,
        -3.52500044e-02,  1.72118068e-01,  2.39268150e-02,
        -4.59873825e-02, -1.53676439e-02, -6.90000057e-02,
        -2.42189746e-02,  4.69901301e-02, -4.26594578e-02,
         1.77797198e-01,  1.67332813e-01, -1.55868515e-01,
         1.18976198e-01,  2.76787281e-01, -1.08411029e-01,
        -2.17029244e-01, -1.75234288e-01, -1.65824452e-03,
         1.92876477e-02,  1.91417605e-01,  1.21145800e-01,
         1.20335259e-01,  3.13596204e-02, -3.59915830e-02,
         2.86206096e-01, -4.42104368e-03,  9.11245309e-03,
        -2.22171888e-01],
       [ 1.84082597e-01, -2.43237857e-02,  1.37228176e-01,
        -2.33973324e-01,  2.60147512e-01, -8.13591480e-02,
         2.05289871e-02, -1.54858172e-01, -2.11438283e-01,
        -2.15942748e-02, -1.99016348e-01, -1.12275340e-01,
        -2.35612631e-01,  1.94398776e-01, -1.06954217e-01,
         9.14784968e-02, -2.59605814e-02, -1.78503431e-02,
         1.28307298e-01, -1.09763108e-01, -7.09444359e-02,
        -7.54722878e-02,  2.75988970e-02, -8.22319090e-02,
         1.44644499e-01, -1.13479197e-01,  1.60739616e-01,
         1.10495426e-01, -1.37795052e-02,  1.94960579e-01,
         2.03489177e-02,  2.42863238e-01,  1.39529601e-01,
         6.96570948e-02,  1.22800052e-01, -1.19837776e-01,
         1.18707330e-03,  9.94020775e-02,  2.21044868e-01,
        -3.60213369e-02,  1.00475885e-01,  1.52526330e-02,
        -6.49765283e-02, -8.88626128e-02, -1.94103062e-01,
         6.92759827e-03,  2.58739322e-01,  1.64790098e-02,
        -1.27226815e-01,  2.82681167e-01,  2.80548185e-02,
        -1.85868174e-01, -1.01086788e-01, -1.37881070e-01,
         1.77509740e-01,  1.04404772e-02, -1.82820305e-01,
        -4.89345267e-02,  9.45892408e-02,  5.62480949e-02,
         2.62123853e-01, -1.08056108e-03,  2.75444061e-01,
         8.87850299e-03],
       [-2.32743040e-01, -1.86487332e-01, -7.60300532e-02,
         1.24847688e-01,  1.95072755e-01,  1.23723827e-01,
         2.18478501e-01,  5.60142472e-02, -1.71100833e-02,
        -5.43061942e-02,  2.56327868e-01,  1.88256666e-01,
        -2.57431325e-02, -7.56425411e-02, -2.24012822e-01,
        -1.59680784e-01, -2.56312221e-01, -1.79099843e-01,
        -6.57518506e-02,  1.51062235e-01,  2.76868701e-01,
        -2.05894366e-01,  2.58063734e-01, -1.52637839e-01,
        -8.06837454e-02,  1.13397852e-01, -1.42098414e-02,
        -2.74523526e-01,  1.81942448e-01, -1.90729037e-01,
         1.20045580e-01, -2.68203616e-01, -6.29420057e-02,
         2.47645989e-01,  2.81739444e-01, -2.36120552e-01,
        -4.98693138e-02,  1.28069401e-01, -2.39011690e-01,
        -2.68515479e-02, -2.26624712e-01,  6.35261685e-02,
        -8.19516480e-02, -2.49064863e-01, -1.14482768e-01,
        -2.61045277e-01,  2.58917697e-02, -5.29266223e-02,
         2.40613192e-01,  2.38316447e-01,  1.53854728e-01,
         9.55574960e-02, -9.64405313e-02, -9.52718556e-02,
        -6.52003586e-02,  3.85954492e-02, -2.64540762e-01,
         2.78390706e-01,  1.88545004e-01, -1.56660035e-01,
        -1.76930949e-02,  2.12204352e-01, -4.69595753e-02,
        -7.12580383e-02],
       [-1.17832527e-01, -2.49035601e-02,  2.83772051e-01,
        -1.00082032e-01, -2.12546304e-01,  1.90118834e-01,
         1.52378350e-01,  2.76875019e-01, -1.30899772e-01,
        -1.65637642e-01, -1.83892343e-03,  1.18616946e-01,
         1.91772223e-01,  2.02117369e-01, -2.57776111e-01,
        -2.11565077e-01, -2.75640637e-01,  9.34815705e-02,
         1.77457824e-01, -3.47559378e-02,  1.85540259e-01,
         1.05418809e-01,  1.35515004e-01,  1.35946587e-01,
         2.13916861e-02,  1.28825322e-01,  2.70320773e-01,
         1.00819226e-02, -2.03487083e-01,  1.07947633e-01,
        -2.07975656e-01, -5.21905497e-02, -2.55171478e-01,
        -1.03972949e-01,  1.67466760e-01,  5.25035672e-02,
        -2.15592101e-01, -5.58020547e-02,  1.58088773e-01,
        -1.88764166e-02,  1.27942637e-01, -8.95917863e-02,
         1.97363347e-01,  2.31732205e-01, -1.30067244e-01,
        -9.70745385e-02, -1.79020926e-01,  1.29723802e-01,
         1.84278429e-01,  2.13675741e-02,  1.12168983e-01,
        -2.06761926e-01,  4.62572500e-02, -1.55666843e-01,
         4.19782102e-02, -6.94530364e-03, -2.51059294e-01,
        -1.26753166e-01, -2.48804335e-02,  2.48876184e-01,
         1.47115976e-01, -1.08147815e-01, -2.08036929e-01,
         1.33302346e-01],
       [ 2.03933239e-01, -8.28971788e-02, -2.62301356e-01,
         1.48266971e-01, -9.74946171e-02,  7.89680034e-02,
        -2.73853630e-01, -7.33970627e-02, -1.97410025e-02,
        -1.96538895e-01,  1.33314490e-01, -5.88378869e-02,
        -1.53257683e-01, -1.09623730e-01,  9.31496918e-02,
         1.60858959e-01,  4.29994911e-02,  1.07444199e-02,
         3.31574269e-02, -2.99320146e-02, -7.03658834e-02,
         1.33023057e-02, -2.00050678e-02, -2.10147545e-01,
         8.39514062e-02,  1.89947203e-01,  2.52216876e-01,
        -3.62279080e-02,  2.73252130e-01,  1.08155712e-01,
        -2.84194887e-01,  3.64355706e-02, -1.73427194e-01,
        -1.56437129e-01,  5.03281392e-02, -2.44407523e-02,
        -2.53573090e-01, -1.88409418e-01,  1.93230391e-01,
         5.32709211e-02, -1.85031727e-01, -2.39900008e-01,
        -2.16979265e-01, -1.82336494e-01,  5.89379407e-02,
        -5.96555695e-02,  5.30173928e-02, -2.39037588e-01,
         6.00585602e-02,  1.30749822e-01, -1.94267064e-01,
         9.93426591e-02, -4.78390418e-03,  6.98209852e-02,
        -2.19179615e-01, -2.81315356e-01, -2.42479801e-01,
        -9.87928174e-03, -5.12366071e-02, -3.04100197e-03,
         2.14805663e-01,  2.05625698e-01,  2.20458299e-01,
        -2.82355160e-01],
       [-2.11271286e-01, -9.39876065e-02, -1.43593373e-02,
        -3.54180224e-02,  1.90556183e-01, -1.48223028e-01,
        -6.09604418e-02, -7.13390782e-02, -3.62545326e-02,
         1.34468168e-01, -9.05668736e-03,  2.47410819e-01,
        -2.12535232e-01, -1.03691593e-01,  2.38675982e-01,
        -1.61408484e-01,  9.68604535e-02, -2.37288713e-01,
         2.78641969e-01, -5.21746352e-02,  8.04876443e-03,
        -1.59588113e-01, -9.50548649e-02, -1.98073342e-01,
        -2.26524591e-01,  1.94106773e-01, -1.16086543e-01,
        -2.26808012e-01, -1.66492094e-03, -2.15636238e-01,
        -2.61490466e-03, -1.47527292e-01,  1.22417830e-01,
        -2.38018677e-01, -3.44539098e-02,  4.61693816e-02,
        -7.37611717e-03, -2.37938151e-01, -5.38823940e-03,
        -2.57610112e-01,  5.27732745e-02,  4.88614514e-02,
         6.50582016e-02, -1.91557676e-01,  1.57071874e-01,
         2.33536750e-01, -4.12504654e-04,  1.71706006e-01,
         1.78267539e-01, -2.42357418e-01,  2.84275562e-02,
         8.65974873e-02, -7.25190118e-02, -1.97391406e-01,
        -4.59601879e-02, -1.73969597e-01,  3.76707464e-02,
         2.49720335e-01,  3.38401571e-02,  7.07706530e-03,
         7.55254179e-02,  7.63717741e-02,  4.30402793e-02,
        -1.19548813e-01]], dtype=float32)>), (None, <tf.Variable 'actor_2/dense_8/bias:0' shape=(64,) dtype=float32, numpy=
array([-0.0029412 , -0.00300452,  0.00300409,  0.00300107,  0.00299157,
       -0.00291923,  0.00299845, -0.00299935,  0.00299953,  0.00296671,
        0.00294133, -0.00270115, -0.00300485,  0.0030049 ,  0.00300163,
        0.00294916,  0.00299267,  0.00299745, -0.00295329, -0.0030015 ,
        0.00300231,  0.00277326,  0.00300077, -0.00299851, -0.00300479,
       -0.00298186,  0.00294505, -0.00300484,  0.00295397,  0.00300445,
       -0.003002  ,  0.00300468,  0.00296517, -0.00300397,  0.00300306,
        0.00295935,  0.00291322, -0.00296758, -0.00299556, -0.00300423,
       -0.00300186, -0.00298502, -0.00300175,  0.00298804, -0.0030041 ,
       -0.00289887, -0.00297994,  0.00271694, -0.00298989,  0.00299536,
       -0.00298609,  0.00192486, -0.00300494, -0.00300239, -0.00294846,
        0.00298918,  0.00282288, -0.002995  , -0.00296985, -0.00297874,
        0.00297302, -0.00258146,  0.00030315, -0.003001  ], dtype=float32)>), (None, <tf.Variable 'actor_2/dense_9/kernel:0' shape=(64, 64) dtype=float32, numpy=
array([[ 5.3612098e-02,  5.9419956e-02,  8.3398312e-02, ...,
         2.0425862e-01,  1.7188542e-01,  4.4487149e-02],
       [-7.3674969e-02, -1.3705911e-01, -1.2259411e-01, ...,
        -2.0335712e-01, -1.2730594e-01, -1.0471429e-01],
       [ 8.2851805e-02,  6.4921498e-02, -2.4779581e-02, ...,
        -1.7773919e-04, -1.1505780e-01, -9.4501562e-03],
       ...,
       [ 7.3154777e-02,  6.6746838e-02,  4.2326901e-02, ...,
        -8.3257005e-02, -1.7268960e-01, -1.4761600e-01],
       [ 1.6910809e-01, -1.3819095e-01,  8.5467443e-02, ...,
        -1.0950284e-01,  1.6428252e-01, -9.0252928e-02],
       [ 6.1507139e-02,  2.3672697e-03,  8.4384270e-03, ...,
         1.3887784e-01, -1.6801108e-01,  1.4831875e-02]], dtype=float32)>), (None, <tf.Variable 'actor_2/dense_9/bias:0' shape=(64,) dtype=float32, numpy=
array([ 0.00300334, -0.00033623, -0.00299231, -0.00283281,  0.00300298,
        0.00292542,  0.00291993,  0.00289211,  0.00299592,  0.00300439,
       -0.00294491,  0.00300393, -0.00299412,  0.00299472, -0.0029911 ,
       -0.00280463, -0.00297534, -0.00300368,  0.00298391, -0.00299793,
        0.00300321, -0.00300306, -0.00300469,  0.00300309, -0.00285299,
       -0.00300464, -0.00300447, -0.00273062, -0.00299487, -0.00299754,
       -0.0029961 , -0.00300198, -0.00293925, -0.002991  , -0.003001  ,
        0.00299282, -0.00300465, -0.00238783, -0.00296928,  0.00300142,
       -0.0029937 , -0.00295096, -0.00300493,  0.00282279, -0.00027222,
       -0.00299414, -0.00299123, -0.00298777, -0.00022523, -0.00300493,
       -0.00300368,  0.00300195,  0.00297759, -0.0029605 ,  0.00300359,
        0.0030029 , -0.00299019,  0.00300309,  0.00300443, -0.00297389,
       -0.00300477, -0.00299507,  0.00297375, -0.00299719], dtype=float32)>), (None, <tf.Variable 'actor_2/dense_10/kernel:0' shape=(64, 64) dtype=float32, numpy=
array([[-0.1446839 , -0.05752488, -0.05787596, ..., -0.09395881,
         0.0633893 ,  0.08316419],
       [ 0.19952135,  0.20174052, -0.19893634, ..., -0.20451705,
        -0.01396681, -0.18059891],
       [-0.15052065, -0.10148031,  0.11991752, ...,  0.16628125,
        -0.04492241,  0.07885075],
       ...,
       [-0.14534976, -0.1482676 ,  0.0187854 , ..., -0.15124182,
         0.10022474, -0.13141596],
       [-0.00985919,  0.06893023,  0.15834504, ..., -0.03431138,
         0.03673209,  0.12524435],
       [-0.20708556, -0.16761796,  0.03365413, ..., -0.06861877,
        -0.06459159,  0.14069773]], dtype=float32)>), (None, <tf.Variable 'actor_2/dense_10/bias:0' shape=(64,) dtype=float32, numpy=
array([-0.00299767,  0.00300353,  0.00299801, -0.00300103, -0.00299746,
        0.00300257,  0.00299101,  0.00299687, -0.00298712, -0.00299416,
        0.00300195,  0.00300224, -0.00299833,  0.00299795, -0.0030036 ,
        0.00299055, -0.00295739, -0.00298716, -0.00300415, -0.00300356,
       -0.00299809, -0.00300168, -0.00300314,  0.00300134, -0.00299818,
        0.00299564, -0.00299021, -0.00286587,  0.00299545, -0.00299905,
       -0.00300182, -0.00300153,  0.00274044, -0.00299888, -0.00299889,
        0.0029976 , -0.00300187,  0.002996  , -0.00299741, -0.00300112,
       -0.00299921, -0.00300078,  0.00276138, -0.00299638, -0.00299796,
       -0.003002  ,  0.00300262,  0.00299853,  0.00300108,  0.00300103,
       -0.00300481,  0.00300209,  0.00299859,  0.00299927, -0.00300129,
        0.00299792, -0.00300482,  0.00299902, -0.00299851, -0.00300491,
        0.00299811,  0.00300454,  0.00300225, -0.00299767], dtype=float32)>), (None, <tf.Variable 'actor_2/dense_11/kernel:0' shape=(64, 10) dtype=float32, numpy=
array([[ 7.97146112e-02, -1.84895787e-02, -6.72052205e-02,
        -3.72535102e-02,  1.49207562e-01,  2.25630879e-01,
         1.22156605e-01, -2.61268437e-01, -3.39783244e-02,
         2.77750403e-01],
       [ 2.36460254e-01, -2.71433771e-01,  2.08281144e-01,
        -2.69650042e-01,  6.31339550e-02,  1.65101245e-01,
        -1.15550622e-01, -7.43052214e-02,  8.99847448e-02,
        -2.58451819e-01],
       [-2.28501260e-01,  1.85634997e-02, -1.99281469e-01,
        -3.19802538e-02,  1.93988517e-01,  2.70138443e-01,
         2.00839117e-01, -2.35145897e-01, -2.54887342e-01,
        -2.40030587e-01],
       [ 1.26439542e-01,  1.50008366e-01,  1.32039234e-01,
         1.80145487e-01,  6.20659906e-04,  1.30550833e-02,
         2.71474630e-01,  2.56418377e-01, -2.59486258e-01,
         3.36086424e-03],
       [-3.59694399e-02, -2.25493312e-02,  2.75432795e-01,
        -1.15552284e-01,  2.63386101e-01,  1.80926904e-01,
        -1.71138480e-01,  1.83530584e-01, -4.40108869e-03,
        -1.52780786e-01],
       [-2.55660087e-01,  1.11744478e-02,  3.66845801e-02,
        -2.49373674e-01, -6.26514629e-02, -1.29397199e-01,
         2.01633707e-01,  2.54744649e-01, -7.43647618e-03,
        -1.26700774e-01],
       [-2.90235560e-02,  8.03797543e-02, -2.62866974e-01,
         1.58785600e-02, -5.76193146e-02,  9.38478410e-02,
        -2.63186395e-01,  2.66424030e-01,  1.68551102e-01,
        -6.94948733e-02],
       [-1.53459027e-01,  1.42011851e-01,  1.24248698e-01,
        -8.88603926e-02, -2.26606101e-01, -1.70611799e-01,
        -5.20466641e-02, -1.16097748e-01,  1.25959292e-01,
         8.77497047e-02],
       [ 7.03693032e-02, -1.07429653e-01,  1.40105903e-01,
         2.66737998e-01, -1.21929944e-01, -3.06051057e-02,
        -1.46186098e-01, -2.40385577e-01,  2.62996197e-01,
        -7.67740514e-03],
       [-1.79897323e-01,  3.25561501e-02, -2.57933170e-01,
         6.02719225e-02,  2.50431329e-01,  1.05863035e-01,
         4.67419066e-02,  8.32749009e-02,  2.23294720e-01,
        -1.83457896e-01],
       [ 1.73720822e-01,  2.35753790e-01, -3.65993343e-02,
        -1.38507798e-01, -2.15363726e-02, -2.48389855e-01,
        -1.94990560e-01, -1.32846728e-01, -1.24151343e-02,
        -7.44070858e-02],
       [-1.75408259e-01, -2.00453967e-01, -2.46715471e-01,
         5.39028868e-02,  1.74864113e-01, -2.68964231e-01,
        -8.60414747e-03,  9.13795456e-02,  1.49055541e-01,
         4.59360406e-02],
       [ 5.16483262e-02, -2.37454295e-01,  1.98171318e-01,
        -7.77851930e-03,  1.02496274e-01, -1.11679966e-02,
        -2.16106921e-01,  1.27475053e-01,  5.26327267e-02,
         2.42525339e-01],
       [ 2.76086144e-02, -2.40183815e-01, -1.94430321e-01,
         2.57749110e-01,  1.71080641e-02, -2.14728877e-01,
        -1.06279552e-01, -2.18300447e-01,  2.73893028e-01,
        -8.74040872e-02],
       [-2.62071639e-02,  1.65300772e-01, -8.46472979e-02,
        -9.44111794e-02,  6.68880194e-02,  2.78009087e-01,
         4.10042293e-02, -1.66460425e-01,  1.39251515e-01,
        -9.75827575e-02],
       [ 9.49603543e-02, -2.72592418e-02, -1.52078122e-01,
        -1.79792598e-01, -1.10985808e-01,  2.28674002e-02,
         1.73879966e-01, -1.75125226e-01,  1.37965158e-01,
         1.00320213e-01],
       [-1.05496660e-01,  2.22379174e-02,  3.94602939e-02,
        -2.36283451e-01, -2.21616417e-01,  2.51481533e-01,
        -2.72310287e-01,  2.45541096e-01,  9.73740071e-02,
         2.03786999e-01],
       [ 1.90439165e-01, -2.62612551e-01, -2.41162047e-01,
         4.10255678e-02,  2.26203203e-01,  6.42745346e-02,
         2.50960708e-01, -1.46873713e-01, -3.52634899e-02,
        -7.28233019e-04],
       [-2.41096020e-01,  2.47676343e-01, -3.99502814e-02,
         1.92573160e-01,  1.29931092e-01,  1.08920887e-01,
        -4.82857674e-02, -1.38734311e-01,  1.02719769e-01,
        -1.32944807e-01],
       [-2.59265639e-02, -4.77747060e-02, -1.95840433e-01,
         1.67437717e-01,  1.44196395e-02,  2.72752732e-01,
         7.20963404e-02, -3.91227193e-02, -1.09184511e-01,
         1.15767203e-01],
       [-1.64189592e-01,  2.35542990e-02,  2.29604825e-01,
         2.73141533e-01, -5.04208356e-02, -1.35722339e-01,
         1.44617423e-01, -1.01485349e-01,  3.22137475e-02,
         2.72309214e-01],
       [-4.26517203e-02, -1.02719152e-02,  2.43680820e-01,
         2.37310693e-01, -2.01392129e-01,  1.14675216e-01,
         4.96030077e-02, -1.70543686e-01,  1.12306081e-01,
         1.95656940e-01],
       [ 2.55105108e-01, -1.74983963e-01,  2.56811343e-02,
         4.02275249e-02, -1.87783495e-01,  5.48789427e-02,
         5.47253620e-03,  2.28222504e-01,  2.55506597e-02,
        -9.10115708e-03],
       [-2.28072807e-01,  9.45633128e-02, -2.31170714e-01,
        -1.96036845e-01,  1.85352802e-01, -1.79272652e-01,
         2.29683608e-01, -2.36991465e-01, -2.91636754e-02,
        -8.18862841e-02],
       [-1.62820697e-01,  2.78835863e-01, -1.48263589e-01,
         1.79574221e-01,  1.23026639e-01, -2.52770595e-02,
         2.62390107e-01, -1.95404887e-01,  1.16641121e-02,
         2.31679529e-01],
       [-5.12213968e-02, -1.23028010e-01,  6.37154654e-02,
         4.39369418e-02,  7.83893541e-02,  1.02210678e-01,
        -2.81231135e-01, -1.06906585e-01,  7.38947764e-02,
        -3.90298180e-02],
       [-1.12171672e-01, -8.16522762e-02,  6.99640112e-03,
         8.98800138e-03,  8.34761336e-02, -1.85840279e-01,
         2.09418833e-01, -1.05126746e-01,  9.12241116e-02,
         1.96260780e-01],
       [ 4.35835272e-02, -2.16410145e-01,  2.59482652e-01,
         1.86522797e-01, -6.07179105e-02, -2.77555436e-01,
         4.32146043e-02,  2.07669035e-01, -1.68844298e-01,
        -1.62169803e-02],
       [-2.67971009e-01, -2.50758767e-01,  2.87118226e-01,
         1.29548192e-03,  1.70454122e-02,  2.02639341e-01,
        -2.19409913e-01, -2.79883862e-01,  2.28288621e-01,
         5.33044972e-02],
       [ 1.07092030e-01,  2.64901161e-01, -5.79979445e-04,
         1.06969960e-01,  2.73907363e-01,  2.42107213e-01,
         6.23157956e-02,  7.45619014e-02, -1.89805627e-01,
         9.76970568e-02],
       [ 1.75403759e-01,  9.79250818e-02, -1.30196646e-01,
        -3.35970819e-02,  2.04049155e-01,  2.27453396e-01,
         1.05177745e-01,  1.49289146e-01, -2.08154604e-01,
        -1.00769654e-01],
       [-1.74323812e-01, -1.12761870e-01,  9.77037400e-02,
        -2.76198566e-01, -9.67918895e-03,  2.21084639e-01,
         2.20874056e-01,  7.08058327e-02,  2.83594340e-01,
         2.47762486e-01],
       [ 1.93494223e-02, -1.39765933e-01, -2.58220047e-01,
         2.36162499e-01, -8.68702829e-02,  2.08215252e-01,
         2.44110838e-01, -1.39312625e-01, -2.94413604e-02,
        -4.68521863e-02],
       [ 7.08913729e-02,  1.73011094e-01,  7.92986378e-02,
        -1.81791723e-01,  1.72084659e-01,  1.66163713e-01,
         1.52648509e-01,  2.66177803e-01, -5.43076657e-02,
         4.21130843e-02],
       [ 1.13704257e-01, -8.73468444e-02,  2.60226279e-01,
         2.79495329e-01, -2.35593654e-02,  2.54052609e-01,
        -2.60217786e-01,  1.19493835e-01,  1.08635100e-03,
         2.42654711e-01],
       [-1.25108734e-01, -1.57836959e-01,  1.45756572e-01,
         2.37931013e-01, -1.60572544e-01, -1.03068203e-01,
         1.72802031e-01, -7.85274655e-02,  7.55580515e-02,
        -2.41565555e-01],
       [ 1.03836507e-01, -2.27761805e-01,  2.34445095e-01,
         3.20169926e-02, -7.12701911e-03,  1.77914351e-01,
         1.62423760e-01, -7.45639503e-02,  8.35095048e-02,
        -1.14578027e-02],
       [-2.06694379e-01, -1.28223106e-01,  1.82206258e-01,
        -1.82347354e-02,  9.74220335e-02,  2.32544765e-01,
        -1.40070096e-01, -4.98514064e-02, -1.83234915e-01,
        -4.42209579e-02],
       [-1.09308906e-01,  2.32137755e-01,  2.10818455e-01,
         1.06281586e-01,  1.90894589e-01, -9.29860696e-02,
         1.23102859e-01, -1.32536069e-01, -1.99921615e-02,
        -1.14931278e-01],
       [ 1.05687127e-01,  1.29743680e-01, -2.46823326e-01,
         2.77233094e-01,  1.43020466e-01, -4.63720970e-02,
         5.14994450e-02,  2.22621545e-01,  1.88847557e-01,
        -1.72956139e-02],
       [ 8.95084813e-04, -1.12264186e-01,  2.09797412e-01,
         2.30717480e-01, -6.69069588e-02,  2.60065138e-01,
         2.63702452e-01,  2.54670084e-01, -1.84233766e-02,
         2.44754910e-01],
       [ 3.18170786e-02,  2.69441187e-01, -8.45993608e-02,
         1.36338562e-01, -5.51661216e-02,  2.67213762e-01,
         1.54326558e-02,  2.24425733e-01,  9.40941572e-02,
         2.69829690e-01],
       [ 8.21344480e-02, -2.79058725e-01, -2.10388556e-01,
         6.86767921e-02,  1.97151557e-01,  3.17881331e-02,
         2.81908751e-01, -1.60532579e-01,  8.37617442e-02,
        -8.88369009e-02],
       [-9.02503077e-03,  2.08574712e-01,  2.27846861e-01,
        -1.63548626e-04, -7.69462809e-02,  2.43457079e-01,
         1.71995535e-02, -1.21100180e-01, -1.05842717e-01,
        -9.89485905e-02],
       [ 1.84970289e-01, -1.31874174e-01,  2.47481376e-01,
         1.80915743e-01, -1.39013931e-01, -8.24633986e-03,
        -5.15561178e-02,  1.88013703e-01, -1.41292825e-01,
         1.65795773e-01],
       [-4.89490516e-02, -1.40648797e-01, -9.53870174e-03,
         2.74973214e-01, -1.26320636e-02,  2.46962130e-01,
         2.98226867e-02,  1.58668250e-01,  1.94388241e-01,
        -2.54499376e-01],
       [ 2.27800578e-01, -2.70697743e-01,  5.57962572e-03,
        -2.56872475e-01, -1.47885934e-01,  1.74680233e-01,
        -1.21725444e-02,  2.95992531e-02, -5.88183217e-02,
        -1.70435272e-02],
       [-2.43330464e-01, -2.36938506e-01,  5.31652644e-02,
        -3.50336209e-02, -1.46972179e-01,  3.38670686e-02,
        -5.59640899e-02,  5.41217700e-02, -2.83304714e-02,
        -7.78612420e-02],
       [-1.27426639e-01, -2.12242156e-01, -1.89402968e-01,
        -1.73980623e-01, -2.16862619e-01,  2.26971656e-01,
         6.25139400e-02, -2.22751535e-02,  9.33274254e-02,
        -2.76860803e-01],
       [-8.82295370e-02, -1.93593904e-01, -2.23286197e-01,
         1.50534287e-01, -1.52055427e-01,  2.38583073e-01,
        -1.64644912e-01, -2.15352282e-01,  3.04592866e-02,
        -2.61127919e-01],
       [ 1.74928039e-01,  2.96341237e-02,  1.74047261e-01,
         1.17660172e-01,  2.48115122e-01, -1.01321317e-01,
         4.56536189e-02, -1.84587330e-01, -2.00863466e-01,
        -1.67873383e-01],
       [-1.63571119e-01, -2.11874172e-02, -2.20874175e-02,
        -2.87403613e-01,  1.37077183e-01,  1.40256017e-01,
         1.29965216e-01,  7.90896788e-02, -2.08736956e-01,
        -2.01991647e-01],
       [ 2.00840667e-01, -2.64290243e-01, -2.83310115e-01,
         1.48482576e-01,  1.18918911e-01,  2.51376510e-01,
        -7.99639374e-02, -1.88964516e-01, -9.98689383e-02,
        -1.96334898e-01],
       [-6.59547746e-02, -3.54041569e-02, -6.15070872e-02,
        -1.55983701e-01, -2.40226090e-01, -1.44281790e-01,
        -2.66300976e-01,  8.11796486e-02, -2.52247274e-01,
        -2.15062112e-01],
       [-3.61599922e-02,  1.65852472e-01,  1.48083135e-01,
        -2.49934167e-01,  6.55703619e-02, -1.04593523e-01,
         2.22052678e-01,  1.46077618e-01,  2.77101517e-01,
         5.99293113e-02],
       [-1.92813784e-01,  1.03275627e-01, -1.73859626e-01,
        -5.26504964e-02,  9.50398855e-03, -2.18578979e-01,
        -2.06949174e-01,  2.52266556e-01,  2.63546377e-01,
        -2.70816714e-01],
       [ 2.11455122e-01,  1.54649690e-01, -9.42967385e-02,
         1.58046797e-01, -2.27101415e-01, -2.42320925e-01,
         1.55207589e-01,  1.26912534e-01, -1.95129052e-01,
         8.75336230e-02],
       [-2.66582131e-01, -7.61383958e-03, -7.66613856e-02,
         6.80719241e-02,  9.39840898e-02,  3.58603299e-02,
        -2.52346605e-01, -2.65802711e-01, -2.73697942e-01,
        -6.67051896e-02],
       [ 1.99894104e-02,  1.50976226e-01,  5.15870145e-03,
         7.21867159e-02,  6.29193857e-02,  1.76304206e-01,
         1.21330805e-01, -2.03218028e-01, -1.75225642e-02,
         2.76574731e-01],
       [ 2.23425701e-01,  1.45882174e-01,  1.45724818e-01,
        -2.58593947e-01, -2.04151347e-01,  2.05679491e-01,
        -2.09193662e-01, -2.65897721e-01,  2.83505291e-01,
         4.54271473e-02],
       [ 9.73031744e-02,  3.98435490e-03,  2.43283674e-01,
        -2.46029109e-01, -1.15691312e-01, -2.26035565e-01,
        -1.55501679e-01, -4.93951961e-02,  1.56065300e-01,
        -2.41178155e-01],
       [-2.70784438e-01, -1.01423144e-01, -1.69338495e-01,
        -2.24545687e-01,  1.43019736e-01, -2.00475603e-01,
         1.83263004e-01,  2.55044758e-01,  2.09740222e-01,
         2.28005368e-02],
       [ 2.99102664e-02, -1.84215248e-01,  1.98591530e-01,
        -9.01425183e-02, -2.54185826e-01, -2.03349784e-01,
         6.11143112e-02,  2.75498945e-02, -2.39150271e-01,
         2.67685324e-01],
       [ 9.41051990e-02, -2.18841523e-01,  3.24347205e-02,
        -1.62053272e-01, -9.83951390e-02,  1.66928053e-01,
         1.84242219e-01, -5.69721423e-02,  1.87027514e-01,
         8.73750299e-02]], dtype=float32)>), (None, <tf.Variable 'actor_2/dense_11/bias:0' shape=(10,) dtype=float32, numpy=
array([-0.00299998, -0.00299998, -0.00299998, -0.00299998, -0.00299998,
       -0.00299998, -0.00299998, -0.00299998, -0.00299998, -0.00299998],
      dtype=float32)>)).

argmax2

In [ ]:
idx = tf.expand_dims(tf.argmax(prob, 1),1)

In [392]:
argmax2

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([4, 6, 4, 6, 6])>

In [388]:
new_locations

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.18297458, -0.32414532],
       [ 0.07010579,  0.6692085 ],
       [-0.68093157,  0.5190487 ],
       [ 0.43853927, -0.91252923],
       [ 0.291641  ,  0.9541609 ]], dtype=float32)>

In [386]:
-0.04366803 - -0.18297458

0.13930655

In [384]:
old_locations

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.04366803, -0.6686702 ],
       [ 0.6036005 ,  0.18465686],
       [-0.65384126,  0.84083104],
       [-0.6377001 ,  0.26406264],
       [-0.5929303 ,  0.22703886]], dtype=float32)>

In [385]:
new_locations

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.18297458, -0.32414532],
       [ 0.07010579,  0.6692085 ],
       [-0.68093157,  0.5190487 ],
       [ 0.43853927, -0.91252923],
       [ 0.291641  ,  0.9541609 ]], dtype=float32)>

In [376]:
env.locations[1, 6]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.07010579, 0.6692085 ], dtype=float32)>

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.18297458, -0.32414532],
       [ 0.07010579,  0.6692085 ],
       [-0.68093157,  0.5190487 ],
       [ 0.43853927, -0.91252923],
       [ 0.291641  ,  0.9541609 ]], dtype=float32)>

In [369]:
env.locations[1, 2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.21057177,  0.07490659], dtype=float32)>

In [367]:
[[1, 2]]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.21057177,  0.07490659], dtype=float32)>

In [366]:
argmax

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([4, 6, 4, 6, 6])>